server:
  port: 9192

spring:
    datasource:
      username: root
      password: iamGod@293
      url: jdbc:mysql://localhost:3306/saltshaker
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        format_sql: true
